config/routes.rb
Dndomator::Application.routes.draw do
  resources :achievement_instances

  resources :achievements do
    collection do
      get 'list' => 'achievements#index', :list => true
    end
  end
  resources :quests do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :skill_challenges do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :treasures do
    member do
      match 'assign/:cid' => 'treasures#give', :as => :give, :method => :put
      put 'giveall'
    end
  end

  root :to => 'encounters#index'

  resources :items do
    collection do
      get 'auto_create'
    end
  end

  resources :encounters do
    member do
      put 'complete'
    end
  end

  resources :monsters do
    collection do
      get 'auto_create'
    end
  end

  resources :heros do
    collection do
      put 'assign_experience'
      get 'details' => 'heros#index', :details => true
    end
  end

end

app/models/quest.rb
class Quest < ActiveRecord::Base

  def self.kinds
    ["major", "minor"]
  end

  kinds.each_with_index do |t|
    define_method("#{t}?") { kind == t }
  end

  def experience
    Quest.experience[self.level - 1] * ((self.major?) ? Hero.heros().length : 1);
  end

  attr_accessible :completed, :description, :kind, :level, :name, :succeded
  validates :kind, :inclusion => { :in => Quest.kinds }

  private
    def self.experience
      [100, 125, 150, 175, 200, 250, 300, 350, 400, 500, 600, 700, 800, 1000, 1200, 1400, 1600, 2000, 2400, 2800, 3200, 4150, 5100, 6050, 7000, 9000, 11000, 13000, 15000, 19000]
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all(:order => "completed ASC, level DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quests }
    end
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
    @quest = Quest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quest }
    end
  end

  # GET /quests/new
  # GET /quests/new.json
  def new
    @quest = Quest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quest }
    end
  end

  # GET /quests/1/edit
  def edit
    @quest = Quest.find(params[:id])
  end

  def failure
    @quest = Quest.find(params[:id])
    unless @quest.completed
      @quest.completed = true
      @quest.succeded = false
    end
    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest failed!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  def success
    @quest = Quest.find(params[:id])
    unless @quest.completed
      @quest.completed = true
      @quest.succeded = true
      Hero.assign_experience @quest.experience
    end
    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest completed!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(params[:quest])

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render json: @quest, status: :created, location: @quest }
      else
        format.html { render action: "new" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quests/1
  # PUT /quests/1.json
  def update
    @quest = Quest.find(params[:id])

    respond_to do |format|
      if @quest.update_attributes(params[:quest])
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy

    respond_to do |format|
      format.html { redirect_to quests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.haml
= form_for @quest, :html => {:class => "form-horizontal" } do |f|
  - if @quest.errors.any?
    #error_explanation
      %div{:class => "alert alert-error"}
        %h2= "#{pluralize(@quest.errors.count, "error")} prohibited this quest from being saved:"
        %ul
          - @quest.errors.full_messages.each do |msg|
            %li= msg
  - @quest.level ||= Hero.first.level

  %fieldset
    %div.control-group
      = f.label :name, :class => "control-label"
      %div.controls
        = f.text_field :name, :class => "input-xlarge"
    %div.control-group
      = f.label :kind, :class => "control-label"
      %div.controls
        = f.select :kind, Quest.kinds.map{ |k| [k.capitalize, k] }
    %div.control-group
      = f.label :descriptioon, :class => "control-label"
      %div.controls
        = f.text_area :description, :class => "input-xlarge"
    %div.control-group
      = f.label :level, :class => "control-label"
      %div.controls
        = f.number_field :level
    %label.radio
      = f.check_box :completed
      = "Completed"
      = f.check_box :succeded
      = "Succeded"
    %div.form-actions
      = f.submit 'Save', :class => "btn btn-primary"

app/views/quests/edit.html.haml
%h1 Editing quest

= render 'form'

= link_to 'Show', @quest
\|
= link_to 'Back', quests_path

app/views/quests/index.html.haml
%div.page-header
  %h1 Quests

= link_to 'New Quest', new_quest_path, :class => "btn btn-primary"

%table{:class => "table table-striped table-bordered","data-provides" => "rowlink"}
  %thead
    %tr
      %th Name
      %th Kind
      %th Level

  %tbody
  - @quests.each do |quest|
    %tr{:class => (quest.completed) ? (quest.succeded) ? "success" : "error" : "progress"}
      %td= link_to quest.name, quest
      %td= quest.kind
      %td= quest.level

app/views/quests/new.html.haml
%h1 New quest

= render 'form'

= link_to 'Back', quests_path

app/views/quests/show.html.haml
%div.page-header
  %h2
    = "#{@quest.name} (#{(@quest.completed) ? (@quest.succeded) ? "succeded" : "failed" : "progress"})"
  %p="Level #{@quest.level} (#{@quest.experience} EXP)"

%div{:class => "row-fluid"}
  %div{:class => "span4 well"}
    %ul
      %li.nav-header DESCRIPTION
      - @quest.description.split(/\n\W*\n/).each do |b|
        %li= b
  %div.span3.well
    = button_to 'Complete', success_quest_path(@quest), :method => :put, :class => "btn btn-success"
    = button_to 'Fail', failure_quest_path(@quest), :method => :put, :class => "btn btn-danger"

%div{:class => "row-fluid"}
  %div.span3
    = button_to 'Edit', edit_quest_path(@quest), :method => :get, :class => "btn btn-primary"
  %div.span3
    = button_to 'Delete', quest_path(@quest), :method => :delete, :confirm => "Are you sure you want to delete the skill challenge #{@quest.name}?", :class => "btn btn-danger"
  %div.span3
    = button_to 'Back', quests_path, :method => :get, :class => "btn btn-primary"