config/routes.rb
Dndomator::Application.routes.draw do
  resources :achievement_instances

  resources :achievements do
    collection do
      get 'list' => 'achievements#index', :list => true
    end
  end
  resources :quests do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :skill_challenges do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :treasures do
    member do
      match 'assign/:cid' => 'treasures#give', :as => :give, :method => :put
      put 'giveall'
    end
  end

  root :to => 'encounters#index'

  resources :items do
    collection do
      get 'auto_create'
    end
  end

  resources :encounters do
    member do
      put 'complete'
    end
  end

  resources :monsters do
    collection do
      get 'auto_create'
    end
  end

  resources :heros do
    collection do
      put 'assign_experience'
      get 'details' => 'heros#index', :details => true
    end
  end

end

app/models/skill_challenge.rb
class SkillChallenge < ActiveRecord::Base
  attr_accessible :completed, :complexity, :context, :failure, :level, :name, :primary_skill, :secondary_skill, :succeded, :success, :progress_success, :progress_failure

  def experience
    return SkillChallenge.experience[self.level - 1] * self.complexity
  end

  def number_of_success
    return SkillChallenge.success[self.complexity - 1]
  end

  def number_of_failures
    return 3
  end

  private
  def self.experience
    [100, 125, 150, 175, 200, 250, 300, 350, 400, 500, 600, 700, 800, 1000, 1200, 1400, 1600, 2000, 2400, 2800, 3200, 4150, 5100, 6050, 7000, 9000, 11000, 13000, 15000, 19000]
  end
  def self.success
    [4, 6, 8, 10, 12]
  end
end

app/controllers/skill_challenges_controller.rb
class SkillChallengesController < ApplicationController
  # GET /skill_challenges
  # GET /skill_challenges.json
  def index
    @skill_challenges = SkillChallenge.all(:order => "completed ASC, level DESC");

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skill_challenges }
    end
  end

  # GET /skill_challenges/1
  # GET /skill_challenges/1.json
  def show
    @skill_challenge = SkillChallenge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill_challenge }
    end
  end

  # GET /skill_challenges/new
  # GET /skill_challenges/new.json
  def new
    @skill_challenge = SkillChallenge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill_challenge }
    end
  end

  # GET /skill_challenges/1/edit
  def edit
    @skill_challenge = SkillChallenge.find(params[:id])
  end

  # POST /skill_challenges
  # POST /skill_challenges.json
  def create
    @skill_challenge = SkillChallenge.new(params[:skill_challenge])
    check_completion @skill_challenge

    respond_to do |format|
      if @skill_challenge.save
        format.html { redirect_to @skill_challenge, notice: 'Skill challenge was successfully created.' }
        format.json { render json: @skill_challenge, status: :created, location: @skill_challenge }
      else
        format.html { render action: "new" }
        format.json { render json: @skill_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def failure
    @skill_challenge = SkillChallenge.find(params[:id])
    if !@skill_challenge.completed
      @skill_challenge.progress_failure += 1;
      check_completion @skill_challenge
    end
    respond_to do |format|
      if @skill_challenge.save
        format.html { redirect_to @skill_challenge, notice: 'Failure annotated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def success
    @skill_challenge = SkillChallenge.find(params[:id])
    unless @skill_challenge.completed
      @skill_challenge.progress_success += 1;
      check_completion @skill_challenge
      if @skill_challenge.succeded
        Hero.assign_experience @skill_challenge.experience
      end
    end
    respond_to do |format|
      if @skill_challenge.save
        format.html { redirect_to @skill_challenge, notice: 'Success annotated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skill_challenges/1
  # PUT /skill_challenges/1.json
  def update
    @skill_challenge = SkillChallenge.find(params[:id])
    @skill_challenge.attributes = params[:skill_challenge]
    check_completion @skill_challenge

    respond_to do |format|
      if @skill_challenge.update_attributes(params[:skill_challenge])
        format.html { redirect_to @skill_challenge, notice: 'Skill challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_challenges/1
  # DELETE /skill_challenges/1.json
  def destroy
    @skill_challenge = SkillChallenge.find(params[:id])
    @skill_challenge.destroy

    respond_to do |format|
      format.html { redirect_to skill_challenges_url }
      format.json { head :no_content }
    end
  end

  private
  def check_completion skill_challenge
    if skill_challenge.number_of_failures == skill_challenge.progress_failure
      skill_challenge.completed = true
      skill_challenge.succeded = false
    elsif skill_challenge.number_of_success == skill_challenge.progress_success
      skill_challenge.completed = true
      skill_challenge.succeded = true
    else
      skill_challenge.completed = false
      skill_challenge.succeded = false
    end
  end
end

app/helpers/skill_challenges_helper.rb
module SkillChallengesHelper
end

app/views/skill_challenges/_form.html.haml
= form_for @skill_challenge, :html => {:class => "form-horizontal" } do |f|
  - if @skill_challenge.errors.any?
    #error_explanation
      %div{:class => "alert alert-error"}
        %h2= "#{pluralize(@skill_challenge.errors.count, "error")} prohibited this skill_challenge from being saved:"
        %ul
          - @skill_challenge.errors.full_messages.each do |msg|
            %li= msg

  - @skill_challenge.progress_success ||= 0
  - @skill_challenge.progress_failure ||= 0

  %fieldset
    %div.control-group
      = f.label :name, :class => "control-label"
      %div.controls
        = f.text_field :name, :class => "input-xlarge"
    %div.control-group
      = f.label :context, :class => "control-label"
      %div.controls
        = f.text_area :context, :class => "input-xlarge"
    %div.control-group
      = f.label :complexity, :class => "control-label"
      %div.controls
        = f.number_field :complexity
    %div.control-group
      = f.label :level, :class => "control-label"
      %div.controls
        = f.number_field :level
    %div.control-group
      = f.label :primary_skill, :class => "control-label"
      %div.controls
        = f.text_area :primary_skill, :class => "input-xlarge"
    %div.control-group
      = f.label :secondary_skill, :class => "control-label"
      %div.controls
        = f.text_area :secondary_skill, :class => "input-xlarge"
    %div.control-group
      = f.label :success, :class => "control-label"
      %div.controls
        = f.text_area :success, :class => "input-xlarge"
    %div.control-group
      = f.label :failure, :class => "control-label"
      %div.controls
        = f.text_area :failure, :class => "input-xlarge"
    %div.control-group
      = f.label :progress_success, :class => "control-label"
      %div.controls
        = f.number_field :progress_success
    %div.control-group
      = f.label :progress_failure, :class => "control-label"
      %div.controls
        = f.number_field :progress_failure
    %div.form-actions
      = f.submit 'Save', :class => "btn btn-primary"

app/views/skill_challenges/edit.html.haml
%h1 Editing skill_challenge

= render 'form'

= link_to 'Show', @skill_challenge
\|
= link_to 'Back', skill_challenges_path

app/views/skill_challenges/index.html.haml
%div.page-header
  %h1 Skill Challenges

= link_to 'New Skill challenge', new_skill_challenge_path, :class => "btn btn-primary"

%table{:class => "table table-striped table-bordered","data-provides" => "rowlink"}
  %thead
    %tr
      %th Name
      %th Context
      %th Complexity
      %th Level

  %tbody
  - @skill_challenges.each do |skill_challenge|
    %tr{:class => (skill_challenge.completed) ? (skill_challenge.succeded) ? "success" : "error" : "progress"}
      %td= link_to skill_challenge.name, skill_challenge
      %td= skill_challenge.context
      %td= skill_challenge.complexity
      %td= skill_challenge.level

app/views/skill_challenges/new.html.haml
%h1 New Skill Challenge

= render 'form'

= link_to 'Back', skill_challenges_path

app/views/skill_challenges/show.html.haml
%div.page-header
  %h2
    = "#{@skill_challenge.name} (#{(@skill_challenge.completed) ? (@skill_challenge.succeded) ? "succeded" : "failed" : "progress"})"
  %p="Complexity: #{@skill_challenge.complexity} (#{@skill_challenge.number_of_success} success before #{@skill_challenge.number_of_failures} failure)"
  %p="Level #{@skill_challenge.level} #{@skill_challenge.experience} EXP)"

%div{:class => "row-fluid well"}
  %div{:class => "span4"}
    %ul
      %li.nav-header CONTEXT
      - @skill_challenge.context.split(/\n\W*\n/).each do |b|
        %li= b
      %li.nav-header SUCCESS
      - @skill_challenge.success.split(/\n\W*\n/).each do |b|
        %li= b
      %li.nav-header FAILURE
      - @skill_challenge.failure.split(/\n\W*\n/).each do |b|
        %li= b
  %div{:class => "span4"}
    %ul
      %li.nav-header PRIMARY SKILLS
      - @skill_challenge.primary_skill.split(/\n\W*\n/).each do |b|
        %li= b
      %li.nav-header SECONDARY SKILLS
      - @skill_challenge.secondary_skill.split(/\n\W*\n/).each do |b|
        %li= b

%div{:class => "row-fluid well"}
  %div.span3
    = button_to 'SUCCESS', success_skill_challenge_path(@skill_challenge), :method => :put, :class => "btn btn-success btn-large"
  %div.span3
    %h1
      %span.text-success= @skill_challenge.progress_success
      %span="/"
      %span.text-error= @skill_challenge.progress_failure
  %div.span3
    = button_to 'FAILURE', failure_skill_challenge_path(@skill_challenge), :method => :put, :class => "btn btn-danger btn-large"

%div{:class => "row-fluid"}
  %div.span3
    = button_to 'Edit', edit_skill_challenge_path(@skill_challenge), :method => :get, :class => "btn btn-primary"
  %div.span3
    = button_to 'Delete', skill_challenge_path(@skill_challenge), :method => :delete, :confirm => "Are you sure you want to delete the skill challenge #{@skill_challenge.name}?", :class => "btn btn-danger"
  %div.span3
    = button_to 'Back', skill_challenges_path, :method => :get, :class => "btn btn-primary"