config/routes.rb
Dndomator::Application.routes.draw do
  resources :achievement_instances

  resources :achievements do
    collection do
      get 'list' => 'achievements#index', :list => true
    end
  end
  resources :quests do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :skill_challenges do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :treasures do
    member do
      match 'assign/:cid' => 'treasures#give', :as => :give, :method => :put
      put 'giveall'
    end
  end

  root :to => 'encounters#index'

  resources :items do
    collection do
      get 'auto_create'
    end
  end

  resources :encounters do
    member do
      put 'complete'
    end
  end

  resources :monsters do
    collection do
      get 'auto_create'
    end
  end

  resources :heros do
    collection do
      put 'assign_experience'
      get 'details' => 'heros#index', :details => true
    end
  end

end

app/models/treasure.rb
class Treasure < ActiveRecord::Base

  has_many :treasure_components
  has_many :items, :through => :treasure_components
  accepts_nested_attributes_for :items
  attr_accessible :description, :level, :quantity, :quantity_assigned, :packet, :items

  def complete?
    self.treasure_components.each do |component|
      return false unless component.complete?
    end
    return true
  end

  def self.next_packet level
    packet = 1
    packet += 1 while !Treasure.where("level = ? AND packet = ?", level, packet).empty?
    return packet
  end
end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
  # GET /treasures
  # GET /treasures.json
  def index
    @treasures = Treasure.all :order => "level DESC"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @treasures }
    end
  end

  # GET /treasures/1
  # GET /treasures/1.json
  def show
    @treasure = Treasure.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @treasure }
    end
  end

  # GET /treasures/new
  # GET /treasures/new.json
  def new
    @treasure = Treasure.new
		@new = true
		@edit = false
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @treasure }
    end
  end

  # GET /treasures/1/edit
  def edit
		@new = false
		@edit = true
    @treasure = Treasure.find(params[:id])
  end

  def give
    @treasure = Treasure.find(params[:id])
    @component = @treasure.treasure_components.find(params[:cid])
    to_give = @component.quantity - @component.quantity_assigned
    unless @component.update_attribute(:quantity_assigned, to_give + @component.quantity_assigned)
      raise ActiveRecord::Rollback, "Error #{@components.errors.to_s}"
    end

    respond_to do |format|
      format.html { redirect_to @treasure, notice: 'Treasure was successfully assigned.' }
      format.json { render json: @treasure }
    end
  end

  def giveall
    @treasure = Treasure.find(params[:id])
    @treasure.treasure_components.each do |component|
      to_give = component.quantity - component.quantity_assigned
      unless component.update_attribute(:quantity_assigned, to_give + component.quantity_assigned)
        raise ActiveRecord::Rollback, "Error #{components.errors.to_s}"
      end
    end

    respond_to do |format|
      format.html { redirect_to @treasure, notice: 'Treasure was successfully assigned.' }
      format.json { render json: @treasure }
    end
  end

  # POST /treasures
  # POST /treasures.json
  def create

    @treasure = Treasure.new(params[:treasure])
    components = create_components @treasure
    @treasure.save!
    components.each do |component|
      record = TreasureComponent.new(component)
      raise ActiveRecord::Rollback, "Error #{record.errors.to_s}" unless record.save
    end

    respond_to do |format|
      if true
        format.html { redirect_to @treasure, notice: 'Treasure was successfully created.' }
        format.json { render json: @treasure, status: :created, location: @treasure }
      else
        format.html { render action: "new" }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /treasures/1
  # PUT /treasures/1.json
  def update
    @treasure = Treasure.find(params[:id])

    components = create_components @treasure
    @treasure.save!
    TreasureComponent.where(:treasure_id => @treasure.id).delete_all
    components.each do |component|
      record = TreasureComponent.new(component)
      raise ActiveRecord::Rollback, "Error #{record.errors.to_s}" unless record.save
    end

    respond_to do |format|
      if @treasure.update_attributes(params[:treasure])
        format.html { redirect_to @treasure, notice: 'Treasure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_components treasure
    components = []
    params[:component][:ids].each do |item, value|
      component = {}
      next unless value == "true"
      component[:treasure] = treasure
      component[:item] = Item.find(item)
      component[:quantity] = params[:component]['quantity'][item]
      component[:description] = params[:component]['description'][item]
      component[:quantity_assigned] = params[:component]['quantity_assigned'][item]
      component[:hero] = params[:component]['hero'][item] == "" ? nil : Hero.find(params[:component]['hero'][item])
      components << component
    end
    return components
  end

  # DELETE /treasures/1
  # DELETE /treasures/1.json
  def destroy
    @treasure = Treasure.find(params[:id])
    @treasure.destroy

    respond_to do |format|
      format.html { redirect_to treasures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/treasures_helper.rb
module TreasuresHelper
end

app/views/treasures/_form.html.haml
= form_for @treasure, :html => {:class => "form-horizontal" } do |f|
  - if @treasure.errors.any?
    #error_explanation
      %div{:class => "alert alert-error"}
        %h2= "#{pluralize(@treasure.errors.count, "error")} prohibited this treasure from being saved:"
        %ul
          - @treasure.errors.full_messages.each do |msg|
            %li= msg

  %fieldset
    %div.form-actions
      = f.submit 'Save', :class => "btn btn-primary"
    - @treasure.level ||= Hero.first.level
    %div.control-group
      = f.label :description, :class => "control-label"
      %div.controls
        = f.text_field :description
    %div.control-group
      = f.label :level, :class => "control-label"
      %div.controls
        = f.number_field :level

    %ul{:class => "nav nav-list"}
      %li{:class => "nav-header", :id => "cmd-setup"} ITEMS
      %div{:id => "items" }
        - Item.all(:order => "level DESC, name").each do |item|
          - next if @new and item.level > 0 and TreasureComponent.where(:item_id => item.id).present?
          %li
            %div{:class => "controls-row"}
              %label{:class => "span5"}
                = "#{item.name} (#{item.level})"
                = check_box_tag "component[ids][#{item.id}]", true, @treasure.items.include?(item), :class => "item-check"
              - rel = @treasure.treasure_components.where(:item_id => item.id)
              - component = rel.empty? ? nil : rel.first
              - quantity = component.nil? ? 1 : component.quantity
              - quantity_assigned = component.nil? ? 0 : component.quantity_assigned
              - hero_id = (component.nil? or component.hero.nil?) ? -1 : component.hero.id
              - description = component.nil? ? "" : component.description
              = number_field_tag "component[quantity][#{item.id}]", quantity, :class => "input-mini span2"
              = number_field_tag "component[quantity_assigned][#{item.id}]", quantity_assigned, :class => "input-mini span2"
              = text_field_tag "component[description][#{item.id}]", description, :class => "input-mini span2"
              = select_tag "component[hero][#{item.id}]", options_from_collection_for_select(Hero.all, 'id', 'name', hero_id), :include_blank => true

app/views/treasures/edit.html.haml
%h1 Editing treasure

= render 'form'

= link_to 'Show', @treasure
\|
= link_to 'Back', treasures_path

app/views/treasures/index.html.haml
%div.page-header
  %h1 Treasures

= link_to 'New Treasure', new_treasure_path, :class => "btn btn-primary"

%table{:class => "table table-striped table-bordered","data-provides" => "rowlink"}
  %thead
    %tr
      %th Description
      %th Level
      %th Items
      %th Action
  %tbody
    - @treasures.sort { |x,y| (x.level > y.level) ? -1 : (x.level < y.level) ? +1 : x.complete? ? +1 : y.complete? ? -1 : 0 }.each do |treasure|
      %tr{:class => (treasure.complete?) ? "success" : ""}
        %td= link_to treasure.description, treasure
        %td= treasure.level
        %td.nolink
          - treasure.treasure_components.each do |c|
            - quantity = c.quantity > 1 ? "#{c.quantity} " : ""
            = link_to "[#{quantity}#{c.item.name}]", c.item

        %td= link_to "Give treasure", giveall_treasure_path(treasure), :class => "btn btn-primary nolink", :method => :put

app/views/treasures/new.html.haml
%h1 New treasure

= render 'form'

= link_to 'Back', treasures_path

app/views/treasures/show.html.haml
%div.page-header
  %h2
    = @treasure.description


%table{:class => "table table-striped table-bordered","data-provides" => "rowlink"}
  %thead
    %tr
      %th Description
      %th Item
      %th Quantity
      %th Heros
      %th Action
  %tbody
  - @treasure.treasure_components.each do |component|
    %tr{:class => component.complete? ? "success" : ""}
      %td= component.description
      %td= link_to "#{component.item.name} (#{component.item.level})", item_path(component.item)
      %td="#{component.quantity_assigned}/#{component.quantity}"
      %td.nolink
        - if !component.hero.nil?
          =link_to component.hero.name, component.hero
      %td.nolink= link_to "Assign treasure", give_treasure_path(@treasure, component.id), :method => :put, :class => "btn btn-success"


%div{:class => "row-fluid"}
  %div.span2
    = button_to 'Assign All', giveall_treasure_path(@treasure), :method => :put, :class => "btn btn-success btn-large"
  %div.span2
    = button_to 'Edit', edit_treasure_path(@treasure), :method => :get, :class => "btn btn-primary btn-large"
  %div.span2
    = button_to 'Delete', @treasure, :method => :delete, :confirm => "Are you sure you want to delete this treasure?", :class => "btn btn-danger btn-large"
  %div.span2
    = button_to 'Back', treasures_path, :method => :get, :class => "btn btn-primary btn-large"
  %div.span2
    = button_to 'New', new_treasure_path, :method => :get, :class => "btn btn-primary btn-large"