config/routes.rb
Dndomator::Application.routes.draw do
  resources :achievement_instances

  resources :achievements do
    collection do
      get 'list' => 'achievements#index', :list => true
    end
  end
  resources :quests do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :skill_challenges do
    member do
      put 'success'
      put 'failure'
    end
  end

  resources :treasures do
    member do
      match 'assign/:cid' => 'treasures#give', :as => :give, :method => :put
      put 'giveall'
    end
  end

  root :to => 'encounters#index'

  resources :items do
    collection do
      get 'auto_create'
    end
  end

  resources :encounters do
    member do
      put 'complete'
    end
  end

  resources :monsters do
    collection do
      get 'auto_create'
    end
  end

  resources :heros do
    collection do
      put 'assign_experience'
      get 'details' => 'heros#index', :details => true
    end
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title DnD'o'Mator
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div{:class=>"navbar navbar-inverse navbar-fixed-top"}
      %div.navbar-inner
        %div.container-fluid
          = link_to "DnD'o'Mator", root_url, :class=>"brand"
          %ul.nav
            %li= link_to "Encounters", encounters_path
            %li= link_to "Skill Challenges", skill_challenges_path
            %li= link_to "Quests", quests_path
            %li= link_to "Monsters", monsters_path
            %li= link_to "Treasures", treasures_path
            %li= link_to "Items", items_path
            %li= link_to "Heroes", heros_path
            %li= link_to "Achievements", achievements_path

    %div.container-fluid
      %div.row-fluid
      - if flash[:notice]
        %div{:class => "alert alert-info"}
          =flash[:notice]
      - if flash[:error]
        %div{:class => "alert alert-error"}
          =flash[:error]
      = yield